# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"synth_learner": "00_utils.ipynb"}

modules = ["utils.py"]

doc_url = "https://lgvaz.github.io/fastcook/"

git_url = "https://github.com/lgvaz/fastcook/tree/master/"

def custom_doc_links(name): return None
